Added a metric to export new VPA recommendations
gardener/vpa-exporter pull request #15
Opened 2021-04-12 07:56 UTC by harishmanasa

**The new VPA Recommender updates its recommendation in an annotation on the VPA resources. Hence, an additional metric is introduced to export VPA recommendations from annotations as well.**

Commit 1 (added new metric for recommender): 
Added the new metric vpaGardenerRecommendation.
Extended the updateVPAMetrics function to get recommendations from the new recommender

Commit 2 (metric for new recommender):
Changed the name of the metric to vpaGardenerNewRecommendation to differentiate the old vpa recommendation logic

Commit 3 (metric for recommender:reuse func addReco):
Reused the addReco function with the metric pointer argument instead of defining it twice within the updateVPAMetrics function.

**Release note**:
NONE

2021-04-12 07:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gardener/vpa-exporter?pullRequest=15) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gardener/vpa-exporter?pullRequest=15) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gardener/vpa-exporter?pullRequest=15) it.</sub>

2021-04-12 08:42 UTC, amshuman-kr commented
> Change this name to vpaGardenerNewRecommendation just for a while. I believe that kinda differentiates old vpa recommendation logic from newer one.

Isn't `vpaGardenerRecommendation` already differentiation enough? We shouldn't use time-sensitive variable names.

2021-04-12 08:48 UTC, amshuman-kr requested changes
Thanks for the PR, @harishmanasa! Overall looks very good. Only some minor comments.

2021-04-12 08:48 UTC, amshuman-kr commented on main.go
> +	gstatus                          = "vpa-recommender.gardener.cloud/status"
```suggestion
	gardenerVPARecommendationAnnnotationKey                          = "vpa-recommender.gardener.cloud/status"
```

`gstatus` name doesn't convey the meaning for the constant clearly

2021-04-12 08:48 UTC, amshuman-kr commented on main.go
> +	vpaGardenerNewRecommendation = prometheus.NewGaugeVec(
```suggestion
	vpaGardenerRecommendation = prometheus.NewGaugeVec(
```

2021-04-12 08:48 UTC, amshuman-kr commented on main.go
> +			Help:      "The resource recommendation for a container in the VerticalPodAutoscaler status.",
```suggestion
			Help:      "The resource recommendation for a container by the gardener/vpa-recommender.",
```

2021-04-12 08:48 UTC, amshuman-kr commented on main.go
> +	prometheus.MustRegister(vpaGardenerNewRecommendation)
```suggestion
	prometheus.MustRegister(vpaGardenerRecommendation)
```

2021-04-12 08:48 UTC, amshuman-kr commented on main.go
> +	gardenerVPAStatusJSON, hasGardenerVPAStatusJSON := vpa.ObjectMeta.Annotations[gstatus]
```suggestion
	gardenerVPAStatusJSON, hasGardenerVPAStatusJSON := vpa.ObjectMeta.Annotations[gardenerVPARecommendationAnnnotationKey]
```

2021-04-22 07:01 UTC, amshuman-kr requested changes
Thanks for the changes @harishmanasa.

Using the `metric` parameter in `statusMetricFamilyHelper` to switch between the status and the annotations doesn't really achieve code redundancy.

Also, shouldn't the [namespace](https://github.com/gardener/vpa-exporter/blob/45ee65e0d82dfb96fd38fee4e3638ba985a313d3/main_test.go#L265-L272) for the metric family also change for annotations?

How about introducing a string parameter`metricNamespace string` and a function parameter `getStatusFn func(vpa *vpa.VerticalPodAutoscaler) *vpa.VerticalPodAutoscalerStatus` in place of the `metric string` parameter?

Then in `statusRecommendationMetricFamily`, you can simply call something like below.
```go
    return statusMetricFamilyHelper(vpaNamespace, func(vpa *vpa.VerticalPodAutoscaler) *vpa.VerticalPodAutoscalerStatus) {
        return &vpa.Status
    })
```

And in `statusAnnotationsRecommendationMetricFamily`, you can call something like below.
```go
    return statusMetricFamilyHelper(gardener_vpa, func(vpa *vpa.VerticalPodAutoscaler) *vpa.VerticalPodAutoscalerStatus) {
        gardenerVPAStatusJSON, hasGardenerVPAStatusJSON := v.ObjectMeta.Annotations[gardenerVPARecommendationAnnnotationKey]
        if hasGardenerVPAStatusJSON && gardenerVPAStatusJSON != "" {
            gardenerVPAStatus := &autoscaling.VerticalPodAutoscalerStatus{}
            err := json.Unmarshal([]byte(gardenerVPAStatusJSON), gardenerVPAStatus)
            if err != nil {
		fmt.Println("error in unmarshalling gardenerVPAStatus")
		return nil
            }
        return gardenerVPAStatus
    })
```

With this, you can avoid the if conditions based on `metric` parameter completely in `statusMetricFamilyHelper`.

2021-04-22 07:01 UTC, amshuman-kr commented on main.go
> +		if err == nil {
```suggestion
		if err != nil {
```

2021-04-22 07:01 UTC, amshuman-kr commented on main_test.go
> +				if err == nil {
```suggestion
				if err != nil {
```

2021-05-01 06:03 UTC, amshuman-kr requested changes
Can you please get the unit tests running? I get the following errors.
```sh
$ export GO111MODULE=off
$ make test
[INFO] Test coverage is disabled.
=== RUN   TestRunValidVPA
I0501 11:31:03.078629   32549 main.go:155] Setting up event handlers
I0501 11:31:03.081120   32549 main.go:183] Starting vpa-exporter controller
I0501 11:31:03.081191   32549 main.go:186] Waiting for informer caches to sync
I0501 11:31:03.182689   32549 main.go:191] Starting workers
I0501 11:31:03.182823   32549 main.go:197] Started workers
I0501 11:31:03.183399   32549 main.go:255] Successfully synced 'v/valid'
--- PASS: TestRunValidVPA (1.11s)
=== RUN   TestRunInvalidVPA
I0501 11:31:04.185688   32549 main.go:199] Shutting down workers
I0501 11:31:04.186956   32549 main.go:155] Setting up event handlers
I0501 11:31:04.187876   32549 main.go:183] Starting vpa-exporter controller
I0501 11:31:04.187904   32549 main.go:186] Waiting for informer caches to sync
I0501 11:31:04.288467   32549 main.go:191] Starting workers
I0501 11:31:04.288597   32549 main.go:197] Started workers
W0501 11:31:04.288699   32549 main.go:342] Skipping VerticalPodAutoscaler without targetRef v/empty.
I0501 11:31:04.289278   32549 main.go:255] Successfully synced 'v/empty'
W0501 11:31:04.289319   32549 main.go:342] Skipping VerticalPodAutoscaler without targetRef v/noContainers.
I0501 11:31:04.289343   32549 main.go:255] Successfully synced 'v/noContainers'
E0501 11:31:04.289800   32549 runtime.go:69] Observed a panic: &errors.errorString{s:"inconsistent label cardinality: expected 8 label values but got 7 in prometheus.Labels{\"container\":\"v\", \"name\":\"noContainersWithTargetRef\", \"namespace\":\"v\", \"recommendation\":\"target\", \"resource\":\"cpu\", \"targetKind\":\"Deployment\", \"targetName\":\"v\"}"} (inconsistent label cardinality: expected 8 label values but got 7 in prometheus.Labels{"container":"v", "name":"noContainersWithTargetRef", "namespace":"v", "recommendation":"target", "resource":"cpu", "targetKind":"Deployment", "targetName":"v"})
/Users/i344628/go/src/github.com/gardener/vpa-exporter/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
/Users/i344628/go/src/github.com/gardener/vpa-exporter/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/Users/i344628/go/src/github.com/gardener/vpa-exporter/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/Cellar/go/1.16.2/libexec/src/runtime/panic.go:971
/Users/i344628/go/src/github.com/gardener/vpa-exporter/vendor/github.com/prometheus/client_golang/prometheus/gauge.go:228
/Users/i344628/go/src/github.com/gardener/vpa-exporter/main.go:329
/Users/i344628/go/src/github.com/gardener/vpa-exporter/main.go:405
/Users/i344628/go/src/github.com/gardener/vpa-exporter/main.go:292
/Users/i344628/go/src/github.com/gardener/vpa-exporter/main.go:247
/Users/i344628/go/src/github.com/gardener/vpa-exporter/main.go:257
/Users/i344628/go/src/github.com/gardener/vpa-exporter/main.go:208
/Users/i344628/go/src/github.com/gardener/vpa-exporter/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/Users/i344628/go/src/github.com/gardener/vpa-exporter/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/Users/i344628/go/src/github.com/gardener/vpa-exporter/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/usr/local/Cellar/go/1.16.2/libexec/src/runtime/asm_amd64.s:1371
panic: inconsistent label cardinality: expected 8 label values but got 7 in prometheus.Labels{"container":"v", "name":"noContainersWithTargetRef", "namespace":"v", "recommendation":"target", "resource":"cpu", "targetKind":"Deployment", "targetName":"v"} [recovered]
	panic: inconsistent label cardinality: expected 8 label values but got 7 in prometheus.Labels{"container":"v", "name":"noContainersWithTargetRef", "namespace":"v", "recommendation":"target", "resource":"cpu", "targetKind":"Deployment", "targetName":"v"}

goroutine 14 [running]:
github.com/gardener/vpa-exporter/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/Users/i344628/go/src/github.com/gardener/vpa-exporter/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x16d
panic(0x2324380, 0xc00007a800)
	/usr/local/Cellar/go/1.16.2/libexec/src/runtime/panic.go:971 +0x499
github.com/gardener/vpa-exporter/vendor/github.com/prometheus/client_golang/prometheus.(*GaugeVec).With(0xc00028c4c0, 0xc00022b980, 0x2462b25, 0xa)
	/Users/i344628/go/src/github.com/gardener/vpa-exporter/vendor/github.com/prometheus/client_golang/prometheus/gauge.go:228 +0x132
github.com/gardener/vpa-exporter.addReco(0x2d9f4b0, 0x1, 0x246033f, 0x6, 0xc0001340d4, 0x3, 0x96, 0xfffffffd, 0x0, 0xc0001340d0, ...)
	/Users/i344628/go/src/github.com/gardener/vpa-exporter/main.go:329 +0x593
github.com/gardener/vpa-exporter.(*Controller).updateVPAMetrics(0xc0001005c0, 0xc00046fb80, 0x19, 0xc00046fb80)
	/Users/i344628/go/src/github.com/gardener/vpa-exporter/main.go:405 +0xf8d
github.com/gardener/vpa-exporter.(*Controller).syncHandler(0xc0001005c0, 0xc0002004e0, 0x1b, 0x0, 0xc000044640)
	/Users/i344628/go/src/github.com/gardener/vpa-exporter/main.go:292 +0x2fb
github.com/gardener/vpa-exporter.(*Controller).processNextWorkItem.func1(0xc0001005c0, 0x22f8e20, 0xc00019bc30, 0x0, 0x0)
	/Users/i344628/go/src/github.com/gardener/vpa-exporter/main.go:247 +0x151
github.com/gardener/vpa-exporter.(*Controller).processNextWorkItem(0xc0001005c0, 0x1078201)
	/Users/i344628/go/src/github.com/gardener/vpa-exporter/main.go:257 +0x71
github.com/gardener/vpa-exporter.(*Controller).runWorker(...)
	/Users/i344628/go/src/github.com/gardener/vpa-exporter/main.go:208
github.com/gardener/vpa-exporter/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00007a4c0)
	/Users/i344628/go/src/github.com/gardener/vpa-exporter/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x76
github.com/gardener/vpa-exporter/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00007a4c0, 0x3b9aca00, 0x0, 0x1, 0xc0002e07e0)
	/Users/i344628/go/src/github.com/gardener/vpa-exporter/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0x111
github.com/gardener/vpa-exporter/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc00007a4c0, 0x3b9aca00, 0xc0002e07e0)
	/Users/i344628/go/src/github.com/gardener/vpa-exporter/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x5b
created by github.com/gardener/vpa-exporter.(*Controller).Run
	/Users/i344628/go/src/github.com/gardener/vpa-exporter/main.go:194 +0x2d5

Ginkgo ran 1 suite in 24.754794303s
Test Suite Failed
make: *** [test] Error 1
```

2021-05-01 06:03 UTC, amshuman-kr commented on main_test.go
> +		if getStatusFn(v).Recommendation == nil || getStatusFn(v).Recommendation.ContainerRecommendations == nil {
```suggestion
		status := getStatusFn(v)
		if status.Recommendation == nil || status.Recommendation.ContainerRecommendations == nil {
```
`getStatusFn` is a potentially costly operation involving JSON parsing. Better to invoke it only once and reuse the results. Especially because we are passing the same VPA object as argument each time.

2021-05-01 06:03 UTC, amshuman-kr commented on main_test.go
> +			cr := &getStatusFn(v).Recommendation.ContainerRecommendations[i]
```suggestion
		for i := range status.Recommendation.ContainerRecommendations {
			cr := &status.Recommendation.ContainerRecommendations[i]
```

2021-05-01 06:03 UTC, amshuman-kr commented on main_test.go
> +	}, vs)
```suggestion
	return statusMetricFamilyHelper(gardener_vpa, func(vpa *vpa.VerticalPodAutoscaler) *vpa.VerticalPodAutoscalerStatus {
		gardenerVPAStatus := &autoscaling1.VerticalPodAutoscalerStatus{}
		gardenerVPAStatusJSON, hasGardenerVPAStatusJSON := vpa.ObjectMeta.Annotations[gardenerVPARecommendationAnnnotationKey]
		if hasGardenerVPAStatusJSON && gardenerVPAStatusJSON != "" {
			gardenerVPAStatus := &autoscaling1.VerticalPodAutoscalerStatus{}
			err := json.Unmarshal([]byte(gardenerVPAStatusJSON), gardenerVPAStatus)
			if err != nil {
				fmt.Println("error in unmarshalling gardenerVPAStatus")
				return nil
			}
			return gardenerVPAStatus
		}
		return gardenerVPAStatus
	}, vs)
```
Use the closest viable scope for `gardenerVPAStatus`.

2021-05-01 06:03 UTC, amshuman-kr commented on main_test.go
> +		fmt.Println(err)
```suggestion
		t.Error(err)
```
We should fail the test.

2021-05-01 06:03 UTC, amshuman-kr commented on main_test.go
> +		fmt.Println(err)
```suggestion
		t.Error(err)
```
We should fail the test.

2021-05-03 10:59 UTC, amshuman-kr requested changes
Almost there. Just a couple of questions below.

Also, can you please squash all the commits into one commit?

2021-05-03 10:59 UTC, amshuman-kr commented on main_test.go
> +			// },
Is this supposed to be commented?

2021-05-03 10:59 UTC, amshuman-kr commented on main_test.go
> +	}
Please fail the test here.

2021-05-03 13:51 UTC, harishmanasa commented on main_test.go
> +			// },
No, I've uncommented it

2021-05-03 14:32 UTC, amshuman-kr commented
/squash

2021-06-09 15:36 UTC, amshuman-kr approved these changes
Thanks for the changes @harishmanasa!
/lgtm

2021-06-09 15:39 UTC, merged